source 'https://rubygems.org'

gem "cucumber", "3.1.2"
gem "rspec", "3.5.0"
gem "rspec-core", "3.5.2"
gem "rspec-expectations", "3.5.0"
gem "rspec-support","3.5.0"
gem "rspec-mocks","3.5.0"
gem 'rake'
gem "page-object", "2.0.0"
gem 'data_magic'
gem "selenium-webdriver", "3.141.0"
gem "logger", "1.3.0"
gem "logging","1.8.2"
gem 'pry'
gem 'webdrivers'
gem "watir","6.7.3"
gem "faker", "1.4.3"

