source 'http://rubygems.org'

gem "rubyzip"
gem "selenium-webdriver", "3.141.0"

gem "multi_json","1.11.0"
gem "multi_test","0.1.2"


gem "gherkin", "5.1.0"
gem "cucumber", "3.1.2"
gem 'rest-client', '~> 1.8'


gem "logger", "1.3.0"
gem "logging","1.8.2"
gem "page-object", "2.0.0"
gem "nokogiri", "1.6.6.2"
gem "nokogiri-diff", "0.2.0"
gem "watir","6.7.3"




gem "rspec", "3.5.0"
gem "rspec-core", "3.5.2"
gem "rspec-expectations", "3.5.0"
gem "rspec-support","3.5.0"
gem "rspec-mocks","3.5.0"

gem "faker", "1.4.3"
gem "yml_reader", "0.4"
gem "data_magic", "0.20"

gem "ffi","1.9.6"

gem "require_all","1.3.2"

gem "headless","2.0.0"

gem "watir-scroll","0.1.0"

gem "i18n","0.7.0"

gem 'clipboard', '~> 1.0', '>= 1.0.6'

gem "pry", "0.10.4"

gem 'parallel_tests'
gem 'sauce_whisk'
gem 'rake'
gem 'parallel_split_test'
gem 'rubocop'
gem 'report_builder'